// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXFO-_gWaoWHmQMr88Y6T01HWnUEyhhGA',
    appId: '1:324143885054:web:922453d52e2537b8f493af',
    messagingSenderId: '324143885054',
    projectId: 'mshwar-app-f475e',
    authDomain: 'mshwar-app-f475e.firebaseapp.com',
    storageBucket: 'mshwar-app-f475e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwQ9x3jI_G-Zgyesm2naysMLlu559RiSk',
    appId: '1:324143885054:android:d50ada1f90911482f493af',
    messagingSenderId: '324143885054',
    projectId: 'mshwar-app-f475e',
    storageBucket: 'mshwar-app-f475e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiZXs2It5OXYhNJix2drBKT0leNkZAh44',
    appId: '1:324143885054:ios:508518f03efb1479f493af',
    messagingSenderId: '324143885054',
    projectId: 'mshwar-app-f475e',
    storageBucket: 'mshwar-app-f475e.firebasestorage.app',
    iosBundleId: 'com.mshwar.appcustomer',
  );
}
